export const configSearchNF = [

    { name: 'Nota Fiscal', id: 'nota_fiscal', width: 150 },
    { name: 'Série', id: 'serie', width: 150 },
    { name: 'Data de emissão', id: 'data_emissao', width: 150 },
    { name: 'N° do pedido', id: 'pedido', width: 150 },
    { name: 'Remetente', id: 'remetente', width: 150 },
    { name: 'Destinatário', id: 'destinatario', width: 150 },
    { name: 'Quantidade de Volumes', id: 'quantidade_volumes', width: 150 },
    { name: 'Valor da mercadoria (R$)', id: 'valor_mercadoria', width: 150 },
    { name: 'Romaneio', id: 'romaneio', width: 150 },
    { name: 'CNPJ/CPF Remetente', id: 'cnpj_cpf_remetente', width: 150 },
    { name: 'CNPJ/CPF Recebedor', id: 'cnpj_cpf_recebedor', width: 150 },
    { name: 'Expedidor', id: 'expedidor', width: 150 },
    { name: 'Data de Inclusão', id: 'data_inclusao', width: 150 },
    { name: 'Chave de acesso', id: 'chave_acesso', width: 150 },
    { name: 'Tipo de documento', id: 'tipo_documento', width: 150 },
    { name: 'Código da Empresa', id: 'cod_empresa', width: 150 },
    { name: 'Código Filial', id: 'cod_filial', width: 150 },
    { name: 'CNPJ/CPF Destinatário', id: 'cnpj_cpf_destinatario', width: 150 },
    { name: 'CNPJ/CPF Pagador', id: 'cnpj_cpf_pagador', width: 150 },
    { name: 'Pagador', id: 'pagador', width: 150 },
    { name: 'CNPJ/CPF Expedidor', id: 'cnpj_cpf_expedidor', width: 150 },
    { name: 'Expedidor', id: 'expedidor', width: 150 },
    { name: 'Metragem cúbica (m³)', id: 'met_cubica', width: 150 },
    { name: 'Peso bruto (kg)', id: 'peso_bruto', width: 150 },
    { name: 'Peso líquido (kg)', id: 'peso_liquido', width: 150 },
]