export const configAdvancedSearchDriver = [
  { name: 'CPF', id: 'cpf', width: 150 },
  { name: 'RG', id: 'rg', width: 150 },
  { name: 'Motorista', id: 'nome', width: 150 },
  { name: 'Apelido', id: 'apelido', width: 150 },
  { name: 'Tipo de Motorista', id: 'tipo', width: 150 },
  { name: 'Status', id: 'status', width: 150 },
  { name: 'Celular/Whatsapp', id: 'celular', width: 150 },
  { name: 'Nº Registro (CNH)', id: 'registro', width: 150 },
  { name: 'Categoria (CNH)', id: 'categoria', width: 150 },
  { name: 'Data de Emissão (CNH)', id: 'data_emissao', width: 150 },
  { name: 'Validade (CNH)', id: 'data_validade', width: 150 },
  { name: 'CEP', id: 'cep', width: 150 },
  { name: 'Endereço', id: 'endereco', width: 150 },
  { name: 'Número', id: 'numero', width: 150 },
  { name: 'Complemento', id: 'complemento', width: 150 },
  { name: 'Cidade', id: 'cidade', width: 150 },
  { name: 'UF', id: 'uf', width: 150 },
  { name: 'Bairro', id: 'bairro', width: 150 },
]
