export const configGMSelectionNF = [
  { name: 'N° Nota fiscal', id: 'numero', width: 200 },
  { name: 'Série', id: 'serie', width: 200 },
  { name: 'Pedido', id: 'pedido', width: 200 },
  { name: 'Quantidade de Volumes', id: 'quantidade_volumes', width: 200 },
  { name: 'Peso líquido (kg)', id: 'peso_liquido', width: 200 },
  { name: 'Peso bruto (kg)', id: 'peso_bruto', width: 200 },
  { name: 'Metragem cúbica (m³)', id: 'metragem_cubica', width: 200 },
  { name: 'Valor da mercadoria (R$)', id: 'valor_mercadoria', width: 200 },
  { name: 'Código da Empresa', id: 'codigo_empresa', width: 200 },
  { name: 'Código da Filial', id: 'codigo_filial', width: 200 },
  { name: 'CPF/CNPJ Remetente', id: 'cpf_cnpj_remetente', width: 200 },
  { name: 'Remetente', id: 'nome_fantasia_remetente', width: 200 },
  { name: 'CPF/CNPJ Destinatário', id: 'cpf_cnpj_destinatario', width: 200 },
  { name: 'Destinatário', id: 'nome_fantasia_destinatario', width: 200 },
  { name: 'CPF/CNPJ Pagador', id: 'cpf_cnpj_pagador', width: 200 },
  { name: 'Pagador', id: 'nome_fantasia_pagador', width: 200 },
  { name: 'CPF/CNPJ Transportador', id: 'cpf_cnpj_transportador', width: 200 },
  { name: 'Transportador', id: 'nome_fantasia_transportador', width: 200 },
  { name: 'CPF/CNPJ Expedidor', id: 'cpf_cnpj_expedidor', width: 200 },
  { name: 'Expedidor', id: 'nome_fantasia_expedidor', width: 200 },
  { name: 'CPF/CNPJ Recebedor', id: 'cpf_cnpj_recebedor', width: 200 },
  { name: 'Recebedor', id: 'nome_fantasia_recebedor', width: 200 },
  { name: 'Tipo de documento', id: 'tipo_documento', width: 200 },
  { name: 'Data de emissão', id: 'data_emissao', width: 200 },
  { name: 'Chave de acesso', id: 'chave_acesso', width: 200 },
  { name: 'Romaneio', id: 'romaneio', width: 200 },
  { name: 'Data de Inclusão', id: 'data_inclusao', width: 200 },
]
